### ISSUE TITLE
Not working in XCode 6.3 - but worked in the Beta :-(

### ISSUE THREAD

**Issue by maddoggy1979** [Galeas/CocoaPodUI#33]
as above

**Comment by f33chobits** [comment]
as above

**Comment by maddoggy1979** [comment]
Ah, figured out the DVTPluginCompatibility thing.

As in the instructions, get the UUID of XCode by running this command in terminal:
defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID

Then, add an entry in the correct CocoaPodUI-Info.plist file in the XCode project, and build. Close XCode and reopen.The menu item will be there.
See screenshot below. In this case, I added the UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7

![screen shot 2015-04-15 at 8 27 32 pm](https://cloud.githubusercontent.com/assets/8011491/7156937/304f1dae-e3ae-11e4-98aa-fb88ad97676a.png)
